using System.Collections.Generic;

public enum PrototypeLanguage
{
    English,
    Korean
}

public static class PrototypeLocalization
{
    private static readonly Dictionary<string, string> EnglishByKey = new Dictionary<string, string>
    {
        { "HudTitle", "Prototype HUD" },
        { "Search", "Search" },
        { "Clear", "Clear" },
        { "FilterAll", "All" },
        { "FilterSimulation", "Sim" },
        { "FilterEconomy", "Economy" },
        { "FilterSelected", "Selected" },
        { "FilterLogs", "Logs" },
        { "PanelSimulationStatus", "Simulation Status" },
        { "PanelWorldSnapshot", "World Snapshot" },
        { "PanelTradeFlow", "Trade & Flow" },
        { "PanelEconomyControl", "Economy Control" },
        { "PanelEconomyPressure", "Economy Pressure" },
        { "PanelExpeditionLoop", "Expedition Loop" },
        { "PanelSelectedEntity", "Selected Entity" },
        { "PanelSelectedEconomy", "Selected Economy" },
        { "PanelSelectedDayMetrics", "Selected Day Metrics" },
        { "PanelSelectedTradeSignals", "Selected Trade Signals" },
        { "PanelRecentDayLogs", "Recent Day Logs" },
        { "PanelDungeonRun", "Dungeon Run HUD" },
        { "PanelDungeonBattle", "JRPG Battle HUD" },
        { "PanelDungeonResult", "Run Result Panel" },
        { "PanelDungeonPreElite", "Pre-Elite Decision" },
        { "Prototype", "Prototype" },
        { "PrototypeName", "Dungeon Economy Prototype" },
        { "FrontMenuPrototypeBadge", "Vertical Slice Prototype" },
        { "FrontMenuSubtitle", "Cities gather around dungeons, and every expedition moves the world economy." },
        { "FrontMenuConcept", "Guide frontier cities, dispatch parties into linked dungeons, and keep the mana shard network alive one day at a time." },
        { "FrontActionEnterWorld", "Enter WorldSim" },
        { "FrontMenuHint", "Press Enter or Space to open the guild operations board." },
        { "FrontMenuPillarEconomy", "Balance stock, cover shortages, and turn dungeon output into city stability." },
        { "FrontMenuPillarDispatch", "Recruit parties, choose routes, and time expeditions around readiness and recovery." },
        { "FrontMenuPillarNetwork", "Read the city-dungeon links, road capacity, and pressure across the world board." },
        { "FrontWorldHeadline", "Guild Operations Board" },
        { "FrontWorldBoard", "World Operations Board" },
        { "FrontWorldNoSelection", "Select a city or dungeon on the board to inspect contracts, pressure, and expedition routes." },
        { "FrontWorldSelection", "Selection Brief" },
        { "FrontWorldOverview", "Operations Summary" },
        { "FrontWorldActions", "Action Dock" },
        { "FrontActionRunDay", "Run Day" },
        { "FrontActionRecruit", "Recruit Party" },
        { "FrontActionEnterDungeon", "Enter Dungeon" },
        { "FrontActionAutoTick", "Auto Tick" },
        { "FrontActionPause", "Pause" },
        { "FrontActionResume", "Resume" },
        { "FrontActionResetWorld", "Reset Simulation" },
        { "FrontActionMainMenu", "Main Menu" },
        { "FrontActionOverlayOn", "Overlay On" },
        { "FrontActionOverlayOff", "Overlay Off" },
        { "FrontWorldBoardOverlay", "Network Overlay" },
        { "FrontWorldOverlayReason", "Optional guide layer for reading city-dungeon links, route lanes, and board legends. Turn it off when you want a cleaner world view." },
        { "Step", "Step" },
        { "StepLabel", "Step DungeonRun-Batch-15: Elite Variant Pack + Post-Elite Reward Identity" },
        { "Language", "Language" },
        { "CurrentState", "Current State" },
        { "LastTransition", "Last Transition" },
        { "Visible", "Visible" },
        { "CitiesLabel", "Cities" },
        { "DungeonsLabel", "Dungeons" },
        { "RoadsLabel", "Roads" },
        { "WorldEntities", "World Entities" },
        { "WorldRoutes", "World Routes" },
        { "ResourceCount", "Resource Count" },
        { "ResourceIds", "Resource IDs" },
        { "Route1Id", "Route 1 ID" },
        { "Route1Tags", "Route 1 Tags" },
        { "Route1Link", "Route 1 Link" },
        { "Route1Capacity", "Route 1 Capacity" },
        { "Route1Usage", "Route 1 Usage" },
        { "Route1Utilization", "Route 1 Utilization" },
        { "CameraPosition", "Camera Position" },
        { "Zoom", "Zoom" },
        { "Controls", "Controls" },
        { "TradeOpportunities", "Trade Opportunities" },
        { "ActiveTradeOpportunities", "Active Trade Opportunities" },
        { "UnmetCityNeeds", "Unmet City Needs" },
        { "TradeLink1", "Trade Link 1" },
        { "TradeLink2", "Trade Link 2" },
        { "DungeonOutputHint", "Dungeon Output Hint" },
        { "EconomyControls", "Economy Controls" },
        { "EconomyControlsValue", "[T] Day Step  [R] Reset  [Y] AutoTick On/Off  [P] Pause  [L] Language" },
        { "WorldDay", "World Day" },
        { "AutoTickEnabled", "Auto Tick Enabled" },
        { "AutoTickPaused", "Auto Tick Paused" },
        { "TickInterval", "Tick Interval" },
        { "AutoTickCount", "Auto Tick Count" },
        { "TradeStepCount", "Trade Step Count" },
        { "ExpeditionControls", "Expedition Controls" },
        { "WorldSimControls", "WorldSim Controls" },
        { "DungeonExploreControls", "DungeonRun Explore Controls" },
        { "DungeonExploreControlsValue", "[WASD/Arrows] Move  [Space] Wait  [Q] Retreat" },
        { "DungeonBattleControls", "DungeonRun Battle Controls" },
        { "DungeonBattleControlsValue", "[1] Attack  [2] Skill  [3] Retreat" },
        { "DungeonTargetControls", "DungeonRun Target Controls" },
        { "DungeonTargetControlsValue", "[1] Target 1  [2] Target 2" },
        { "BattleView", "Battle View" },
        { "EncounterName", "Encounter Name" },
        { "EncounterRoomType", "Encounter Room Type" },
        { "Party1", "Party 1" },
        { "Party2", "Party 2" },
        { "Party3", "Party 3" },
        { "Party4", "Party 4" },
        { "RecentBattleLog1", "Recent Battle Log 1" },
        { "RecentBattleLog2", "Recent Battle Log 2" },
        { "RecentBattleLog3", "Recent Battle Log 3" },
        { "RunState", "Run State" },
        { "CurrentDungeon", "Current Dungeon" },
        { "DungeonDanger", "Dungeon Danger" },
        { "ActiveParty", "Active Party" },
        { "CarriedLoot", "Carried Loot" },
        { "CurrentRoom", "Current Room" },
        { "CurrentRoomType", "Current Room Type" },
        { "RoomProgress", "Room Progress" },
        { "TotalPartyHp", "Total Party HP" },
        { "PartyCondition", "Party Condition" },
        { "SustainPressure", "Sustain Pressure" },
        { "NextMajorGoal", "Next Major Goal" },
        { "RunTurnCount", "Run Turn Count" },
        { "EncounterProgress", "Encounter Progress" },
        { "ExitUnlocked", "Exit Unlocked" },
        { "ChestOpened", "Chest Opened" },
        { "EventStatus", "Event Status" },
        { "EventChoice", "Event Choice" },
        { "LootBreakdown", "Loot Breakdown" },
        { "BattleLoot", "Battle Loot" },
        { "ChestLoot", "Chest Loot" },
        { "EventLoot", "Event Loot" },
        { "EliteStatus", "Elite Status" },
        { "EliteEncounter", "Elite Encounter" },
        { "EliteType", "Elite Type" },
        { "EliteHp", "Elite HP" },
        { "EliteIntent", "Elite Intent" },
        { "EliteDefeated", "Elite Defeated" },
        { "EliteName", "Elite Name" },
        { "EliteReward", "Elite Reward" },
        { "EliteRewardStatus", "Elite Reward Status" },
        { "EliteRewardHint", "Elite Reward Hint" },
        { "EliteRewardIdentity", "Elite Reward Label" },
        { "EliteRewardAmount", "Elite Reward Amount" },
        { "PreEliteChoice", "Pre-Elite Choice" },
        { "PreEliteHealAmount", "Pre-Elite Heal Amount" },
        { "EliteBonusRewardEarned", "Elite Bonus Reward Earned" },
        { "EliteBonusRewardAmount", "Elite Bonus Reward Amount" },
        { "LastBattleLog1", "Last Run Log 1" },
        { "LastBattleLog2", "Last Run Log 2" },
        { "LastBattleLog3", "Last Run Log 3" },
        { "BattleState", "Battle State" },
        { "CurrentActor", "Current Actor" },
        { "MonsterName", "Monster Name" },
        { "MonsterHp", "Monster HP" },
        { "Party1Hp", "Party 1 HP" },
        { "Party2Hp", "Party 2 HP" },
        { "Party3Hp", "Party 3 HP" },
        { "Party4Hp", "Party 4 HP" },
        { "Monster1", "Monster 1" },
        { "Monster2", "Monster 2" },
        { "CurrentSelectionPrompt", "Current Selection Prompt" },
        { "MonsterCountPreview", "Encounter Count Preview" },
        { "LastRunLootReturned", "Last Run Loot Returned" },
        { "LastRunSurvivingMembers", "Last Run Surviving Members" },
        { "LastRunClearedEncounters", "Last Run Cleared Encounters" },
        { "LastRunEventChoice", "Last Run Event Choice" },
        { "LastRunLootBreakdown", "Last Run Loot Breakdown" },
        { "Result", "Result" },
        { "DungeonChosen", "Dungeon Chosen" },
        { "TurnsTaken", "Turns Taken" },
        { "LootGained", "Loot Gained" },
        { "SurvivingMembers", "Surviving Members" },
        { "ClearedEncounters", "Cleared Encounters" },
        { "OpenedChests", "Opened Chests" },
        { "DefeatedMonsters", "Defeated Monsters" },
        { "ReturnToWorldPrompt", "Return To World" },
        { "ExpeditionControlsValue", "[G] Recruit Party  [X] Enter Dungeon" },
        { "TotalParties", "Total Parties" },
        { "IdleParties", "Idle Parties" },
        { "ActiveExpeditions", "Active Expeditions" },
        { "AvailableContracts", "Available Contracts" },
        { "ExpeditionSuccesses", "Expedition Successes" },
        { "ExpeditionFailures", "Expedition Failures" },
        { "ExpeditionLootReturned", "Expedition Loot Returned" },
        { "RecentExpeditionLog1", "Recent Expedition Log 1" },
        { "RecentExpeditionLog2", "Recent Expedition Log 2" },
        { "RecentExpeditionLog3", "Recent Expedition Log 3" },
        { "ProducedTotal", "Produced Total" },
        { "ClaimedDungeonOutputs", "Claimed Dungeon Outputs" },
        { "TradedTotal", "Traded Total" },
        { "ProcessedTotal", "Processed Total" },
        { "ConsumedTotal", "Consumed Total" },
        { "CriticalFulfilledTotal", "Critical Fulfilled Total" },
        { "CriticalUnmetTotal", "Critical Unmet Total" },
        { "NormalFulfilledTotal", "Normal Fulfilled Total" },
        { "NormalUnmetTotal", "Normal Unmet Total" },
        { "FulfilledTotal", "Fulfilled Total" },
        { "UnmetTotal", "Unmet Total" },
        { "ShortagesTotal", "Shortages Total" },
        { "ProcessingBlockedTotal", "Processing Blocked Total" },
        { "ProcessingReservedTotal", "Processing Reserved Total" },
        { "UnclaimedDungeonOutputs", "Unclaimed Dungeon Outputs" },
        { "RouteCapacityUsed", "Route Capacity Used" },
        { "SaturatedRoutes", "Saturated Routes" },
        { "CitiesWithShortages", "Cities With Shortages" },
        { "CitiesWithSurplus", "Cities With Surplus" },
        { "CitiesWithProcessing", "Cities With Processing" },
        { "CitiesWithCriticalUnmet", "Cities With Critical Unmet" },
        { "Selected", "Selected" },
        { "SelectedType", "Selected Type" },
        { "SelectedPosition", "Selected Position" },
        { "SelectedId", "Selected ID" },
        { "SelectedTags", "Selected Tags" },
        { "SelectedStat", "Selected Stat" },
        { "SelectedResources", "Selected Resources" },
        { "SelectedResourceRoles", "Selected Resource Roles" },
        { "SelectedSupply", "Selected Supply" },
        { "SelectedNeeds", "Selected Needs" },
        { "SelectedHighPriorityNeeds", "Selected High Priority Needs" },
        { "SelectedNormalPriorityNeeds", "Selected Normal Priority Needs" },
        { "SelectedOutput", "Selected Output" },
        { "SelectedProcessing", "Selected Processing" },
        { "LinkedCity", "Linked City" },
        { "PartiesInCity", "Parties In City" },
        { "ActiveExpeditionsFromCity", "Active Expeditions From City" },
        { "AvailableContract", "Available Contract" },
        { "LinkedDungeon", "Linked Dungeon" },
        { "SelectedCity", "Selected City" },
        { "CurrentCity", "Current City" },
        { "CityManaShardStock", "Mana Shard Stock" },
        { "NeedPressure", "Need Pressure" },
        { "DispatchReadiness", "Dispatch Readiness" },
        { "RecoveryProgress", "Recovery Progress" },
        { "ConsecutiveDispatches", "Consecutive Dispatches" },
        { "DispatchPolicy", "Dispatch Policy" },
        { "CyclePolicy", "Cycle Policy" },
        { "RecommendedRoute", "Recommended Route" },
        { "RecommendedRouteForLinkedCity", "Recommended Route For Linked City" },
        { "RecommendationReason", "Recommendation Reason" },
        { "RecoveryAdvice", "Recovery Advice" },
        { "ExpectedNeedImpact", "Expected Need Impact" },
        { "LastDispatchImpact", "Last Dispatch Impact" },
        { "LastDispatchStockDelta", "Last Dispatch Stock Delta" },
        { "LastNeedPressureChange", "Last Need Pressure Change" },
        { "LastDispatchReadinessChange", "Last Dispatch Readiness Change" },
        { "CityDispatchedFrom", "City Dispatched From" },
        { "FollowedRecommendation", "Followed Recommendation" },
        { "ManaShardsReturned", "Mana Shards Returned" },
        { "StockBefore", "Stock Before" },
        { "StockAfter", "Stock After" },
        { "StockDelta", "Stock Delta" },
        { "NeedPressureBefore", "Need Pressure Before" },
        { "NeedPressureAfter", "Need Pressure After" },
        { "DispatchReadinessBefore", "Dispatch Readiness Before" },
        { "DispatchReadinessAfter", "Dispatch Readiness After" },
        { "RecoveryEta", "Recovery ETA" },
        { "RecommendedPower", "Recommended Power" },
        { "ExpeditionDurationDays", "Expedition Duration Days" },
        { "RewardPreview", "Reward Preview" },
        { "EventPreview", "Event Preview" },
        { "LastExpeditionResult", "Last Expedition Result" },
        { "SelectedStocks", "Selected Stocks" },
        { "SelectedSurplus", "Selected Surplus" },
        { "SelectedDeficit", "Selected Deficit" },
        { "SelectedIdentity", "Selected Identity" },
        { "ReserveStockRule", "Reserve Stock Rule" },
        { "ProcessingPreference", "Processing Preference" },
        { "LastDayProduced", "Last Day Produced" },
        { "LastDayDungeonImports", "Last Day Dungeon Imports" },
        { "LastDayImported", "Last Day Imported" },
        { "LastDayExported", "Last Day Exported" },
        { "LastDayProcessedIn", "Last Day Processed In" },
        { "LastDayProcessedOut", "Last Day Processed Out" },
        { "LastDayProcessedTotal", "Last Day Processed Total" },
        { "LastDayConsumed", "Last Day Consumed" },
        { "LastDayCriticalFulfilled", "Last Day Critical Fulfilled" },
        { "LastDayCriticalUnmet", "Last Day Critical Unmet" },
        { "LastDayNormalFulfilled", "Last Day Normal Fulfilled" },
        { "LastDayNormalUnmet", "Last Day Normal Unmet" },
        { "LastDayFulfilled", "Last Day Fulfilled" },
        { "LastDayUnmet", "Last Day Unmet" },
        { "LastDayShortages", "Last Day Shortages" },
        { "TotalFulfilled", "Total Fulfilled" },
        { "TotalUnmet", "Total Unmet" },
        { "TotalCriticalUnmet", "Total Critical Unmet" },
        { "TotalNormalUnmet", "Total Normal Unmet" },
        { "TotalShortages", "Total Shortages" },
        { "LastDayProcessingBlocked", "Last Day Processing Blocked" },
        { "LastDayProcessingReserved", "Last Day Processing Reserved" },
        { "LastDayClaimedOut", "Last Day Claimed Out" },
        { "SelectedIncomingTrade", "Selected Incoming Trade" },
        { "SelectedOutgoingTrade", "Selected Outgoing Trade" },
        { "SelectedUnmetNeeds", "Selected Unmet Needs" },
        { "RecentDayLog1", "Recent Day Log 1" },
        { "RecentDayLog2", "Recent Day Log 2" },
        { "RecentDayLog3", "Recent Day Log 3" },
        { "ControlsValue", "[LMB] Select  [WASD/Arrows] Pan  [Wheel] Zoom  [Esc] Back" },
        { "PanelDungeonRouteChoice", "Dispatch Planner" },
        { "DungeonRouteControls", "Dungeon Route Controls" },
        { "DungeonRouteControlsValue", "[1] Route 1  [2] Route 2  [Q] Cycle Policy  [Enter] Dispatch  [Esc] Return" },
        { "CurrentRoute", "Current Route" },
        { "RouteRisk", "Route Risk" },
        { "RouteChosen", "Route Chosen" },
        { "RoomPathSummary", "Room Path Summary" },
        { "PartyHpSummary", "Party HP Summary" },
        { "PartyConditionAtEnd", "Party Condition At End" },
        { "RoutePreview1", "Route Preview 1" },
        { "RoutePreview2", "Route Preview 2" },
        { "LastRunDungeon", "Last Run Dungeon" },
        { "LastRunRoute", "Last Run Route" },
        { "BoolOn", "On" },
        { "BoolOff", "Off" },
        { "LanguageEnglish", "English" },
        { "LanguageKorean", "Korean" }
    };

    private static readonly Dictionary<string, string> KoreanByKey = new Dictionary<string, string>(EnglishByKey)
    {
        ["HudTitle"] = "\uD504\uB85C\uD1A0\uD0C0\uC785 HUD",
        ["Search"] = "\uAC80\uC0C9",
        ["Clear"] = "\uC9C0\uC6B0\uAE30",
        ["FilterAll"] = "\uC804\uCCB4",
        ["FilterSimulation"] = "\uC2DC\uBBAC",
        ["FilterEconomy"] = "\uACBD\uC81C",
        ["FilterSelected"] = "\uC120\uD0DD",
        ["FilterLogs"] = "\uB85C\uADF8",
        ["PanelSimulationStatus"] = "\uC2DC\uBBAC\uB808\uC774\uC158 \uC0C1\uD0DC",
        ["PanelWorldSnapshot"] = "\uC6D4\uB4DC \uAC1C\uC694",
        ["PanelTradeFlow"] = "\uAD50\uC5ED \uBC0F \uD750\uB984",
        ["PanelEconomyControl"] = "\uACBD\uC81C \uC81C\uC5B4",
        ["PanelEconomyPressure"] = "\uACBD\uC81C \uC555\uB825",
        ["PanelExpeditionLoop"] = "\uC6D0\uC815 \uC2A4\uCF08\uB808\uD1A4",
        ["PanelSelectedEntity"] = "\uC120\uD0DD \uB300\uC0C1 \uAE30\uBCF8",
        ["PanelSelectedEconomy"] = "\uC120\uD0DD \uB300\uC0C1 \uACBD\uC81C",
        ["PanelSelectedDayMetrics"] = "\uC120\uD0DD \uB300\uC0C1 \uC77C\uC77C \uC9C0\uD45C",
        ["PanelSelectedTradeSignals"] = "\uC120\uD0DD \uB300\uC0C1 \uAD50\uC5ED \uC2E0\uD638",
        ["PanelRecentDayLogs"] = "\uCD5C\uADFC \uC77C\uC77C \uB85C\uADF8",
        ["Prototype"] = "\uD504\uB85C\uD1A0\uD0C0\uC785",
        ["PrototypeName"] = "\uB358\uC804 \uACBD\uC81C \uD504\uB85C\uD1A0\uD0C0\uC785",
        ["FrontMenuPrototypeBadge"] = "\uBC84\uD2F0\uCEEC \uC2AC\uB77C\uC774\uC2A4 \uD504\uB85C\uD1A0\uD0C0\uC785",
        ["FrontMenuSubtitle"] = "\uB3C4\uC2DC\uC640 \uB358\uC804\uC758 \uC5F0\uACB0\uB9DD\uC774 \uC138\uACC4 \uACBD\uC81C\uB97C \uD754\uB4DC\uB294 \uC804\uB7B5 \uD310",
        ["FrontMenuConcept"] = "\uC5F0\uACB0\uB41C \uB3C4\uC2DC\uB97C \uC6B4\uC601\uD558\uACE0 \uC6D0\uC815\uB300\uB97C \uB358\uC804\uC5D0 \uBCF4\uB0B4\uBA70, \uC77C \uB2E8\uC704\uB85C \uC694\uB3D9\uCE58\uB294 \uB9C8\uB098 \uC0E4\uB4DC \uACBD\uC81C\uB97C \uBD99\uC7A1\uC73C\uC2ED\uC2DC\uC624.",
        ["FrontActionEnterWorld"] = "WorldSim \uC9C4\uC785",
        ["FrontMenuHint"] = "Enter \uB610\uB294 Space\uB85C \uAE38\uB4DC \uC6B4\uC601\uD310\uC744 \uC5FD\uB2C8\uB2E4.",
        ["FrontMenuPillarEconomy"] = "\uB3C4\uC2DC \uC7AC\uACE0\uC640 \uBD80\uC871\uBD84\uC744 \uAD00\uB9AC\uD558\uBA70 \uB358\uC804 \uC0B0\uCD9C\uBB3C\uC744 \uC131\uC7A5 \uB3D9\uB825\uC73C\uB85C \uB3CC\uB9BD\uB2C8\uB2E4.",
        ["FrontMenuPillarDispatch"] = "\uD30C\uD2F0\uB97C \uBAA8\uC9D1\uD558\uACE0 \uB8E8\uD2B8\uB97C \uC120\uD0DD\uD574 \uC900\uBE44\uB3C4\uC640 \uD68C\uBCF5 \uC0C1\uD0DC\uC5D0 \uB9DE\uCDF0 \uC6D0\uC815\uC744 \uBCF4\uB0C5\uB2C8\uB2E4.",
        ["FrontMenuPillarNetwork"] = "\uB3C4\uC2DC, \uB358\uC804, \uAD50\uC5ED\uB85C\uAC00 \uC5BD\uD78C \uC6B4\uC601\uD310\uC5D0\uC11C \uD750\uB984\uC744 \uC77D\uACE0 \uACB0\uC815\uC744 \uB0B4\uB9BD\uB2C8\uB2E4.",
        ["FrontWorldHeadline"] = "\uAE38\uB4DC \uC6B4\uC601 \uBCF4\uB4DC",
        ["FrontWorldBoard"] = "\uC138\uACC4 \uC6B4\uC601 \uBCF4\uB4DC",
        ["FrontWorldNoSelection"] = "\uBCF4\uB4DC\uC5D0\uC11C \uB3C4\uC2DC\uB098 \uB358\uC804\uC744 \uC120\uD0DD\uD574 \uACC4\uC57D, \uC218\uC694 \uC555\uB825, \uC6D0\uC815 \uB8E8\uD2B8\uB97C \uD655\uC778\uD558\uC2ED\uC2DC\uC624.",
        ["FrontWorldSelection"] = "\uC120\uD0DD \uB300\uC0C1 \uBE0C\uB9AC\uD504",
        ["FrontWorldOverview"] = "\uC6B4\uC601 \uC694\uC57D",
        ["FrontWorldActions"] = "\uC561\uC158 \uB3C5",
        ["FrontActionRunDay"] = "\uD558\uB8E8 \uC9C4\uD589",
        ["FrontActionRecruit"] = "\uD30C\uD2F0 \uBAA8\uC9D1",
        ["FrontActionEnterDungeon"] = "\uB358\uC804 \uC9C4\uC785",
        ["FrontActionAutoTick"] = "\uC790\uB3D9 \uC9C4\uD589",
        ["FrontActionPause"] = "\uC77C\uC2DC\uC815\uC9C0",
        ["FrontActionResume"] = "\uC7AC\uAC1C",
        ["FrontActionResetWorld"] = "\uC2DC\uBBAC\uB808\uC774\uC158 \uB9AC\uC14B",
        ["FrontActionMainMenu"] = "\uBA54\uC778 \uBA54\uB274",
        ["FrontActionOverlayOn"] = "\uC624\uBC84\uB808\uC774 \uCF1C\uC9D0",
        ["FrontActionOverlayOff"] = "\uC624\uBC84\uB808\uC774 \uAEBC\uC9D0",
        ["FrontWorldBoardOverlay"] = "\uB124\uD2B8\uC6CC\uD06C \uC624\uBC84\uB808\uC774",
        ["FrontWorldOverlayReason"] = "\uB3C4\uC2DC-\uB358\uC804 \uC5F0\uACB0, \uB8E8\uD2B8 \uD750\uB984, \uBCF4\uB4DC \uB808\uC804\uB4DC\uB97C \uC77D\uAE30 \uC27D\uAC8C \uB3D5\uB294 \uC120\uD0DD\uD615 \uAC00\uC774\uB4DC \uB808\uC774\uC5B4\uC785\uB2C8\uB2E4. \uB354 \uB113\uC740 \uC6D4\uB4DC \uD654\uBA74\uC774 \uD544\uC694\uD558\uBA74 \uAEF8 \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
        ["Step"] = "\uB2E8\uACC4",
        ["Language"] = "\uC5B8\uC5B4",
        ["CurrentState"] = "\uD604\uC7AC \uC0C1\uD0DC",
        ["LastTransition"] = "\uB9C8\uC9C0\uB9C9 \uC804\uD658",
        ["Visible"] = "\uD45C\uC2DC \uC911",
        ["EconomyControls"] = "\uACBD\uC81C \uCEE8\uD2B8\uB864",
        ["EconomyControlsValue"] = "[T] \uC77C \uC9C4\uD589  [R] \uB9AC\uC14B  [Y] \uC790\uB3D9 \uD2F1 On/Off  [P] \uC77C\uC2DC\uC815\uC9C0  [L] \uC5B8\uC5B4",
        ["ExpeditionControls"] = "\uC6D0\uC815 \uC870\uC791",
        ["ExpeditionControlsValue"] = "[G] Recruit Party  [X] Enter Dungeon",
        ["TotalParties"] = "\uCD1D \uD30C\uD2F0 \uC218",
        ["IdleParties"] = "\uB300\uAE30 \uD30C\uD2F0",
        ["ActiveExpeditions"] = "\uD65C\uC131 \uC6D0\uC815",
        ["AvailableContracts"] = "\uC774\uC6A9 \uAC00\uB2A5 \uACC4\uC57D",
        ["ExpeditionSuccesses"] = "\uC6D0\uC815 \uC131\uACF5",
        ["ExpeditionFailures"] = "\uC6D0\uC815 \uC2E4\uD328",
        ["ExpeditionLootReturned"] = "\uADC0\uD658 \uC804\uB9AC\uD488",
        ["RecentExpeditionLog1"] = "\uCD5C\uADFC \uC6D0\uC815 \uB85C\uADF8 1",
        ["RecentExpeditionLog2"] = "\uCD5C\uADFC \uC6D0\uC815 \uB85C\uADF8 2",
        ["RecentExpeditionLog3"] = "\uCD5C\uADFC \uC6D0\uC815 \uB85C\uADF8 3",
        ["PartiesInCity"] = "\uB3C4\uC2DC \uB0B4 \uD30C\uD2F0",
        ["PanelDungeonRouteChoice"] = "\uD30C\uACAC \uACC4\uD68D \uD328\uB110",
        ["DungeonRouteControls"] = "\uB358\uC804 \uB8E8\uD2B8 \uC870\uC791",
        ["DungeonRouteControlsValue"] = "[1] Route 1  [2] Route 2  [Q] Cycle Policy  [Enter] Dispatch  [Esc] Return",
        ["CurrentRoute"] = "\uD604\uC7AC \uB8E8\uD2B8",
        ["CurrentRoomType"] = "\uD604\uC7AC \uBC29 \uC720\uD615",
        ["RoomProgress"] = "\uBC29 \uC9C4\uD589\uB3C4",
        ["TotalPartyHp"] = "\uCD1D \uD30C\uD2F0 HP",
        ["PartyCondition"] = "\uD30C\uD2F0 \uC0C1\uD0DC",
        ["SustainPressure"] = "\uC720\uC9C0 \uC555\uBC15",
        ["NextMajorGoal"] = "\uB2E4\uC74C \uC8FC\uC694 \uBAA9\uD45C",
        ["RouteRisk"] = "\uB8E8\uD2B8 \uC704\uD5D8\uB3C4",
        ["RouteChosen"] = "\uC120\uD0DD \uB8E8\uD2B8",
        ["RoomPathSummary"] = "\uBC29 \uACBD\uB85C \uC694\uC57D",
        ["PartyHpSummary"] = "\uD30C\uD2F0 HP \uC694\uC57D",
        ["PartyConditionAtEnd"] = "\uC885\uB8CC \uC2DC \uD30C\uD2F0 \uC0C1\uD0DC",
        ["DungeonChosen"] = "\uC120\uD0DD \uB358\uC804",
        ["RoutePreview1"] = "\uB8E8\uD2B8 \uBBF8\uB9AC\uBCF4\uAE30 1",
        ["RoutePreview2"] = "\uB8E8\uD2B8 \uBBF8\uB9AC\uBCF4\uAE30 2",
        ["LastRunDungeon"] = "\uB9C8\uC9C0\uB9C9 \uB7F0 \uB358\uC804",
        ["LastRunRoute"] = "\uB9C8\uC9C0\uB9C9 \uB7F0 \uB8E8\uD2B8",
        ["ActiveExpeditionsFromCity"] = "\uB3C4\uC2DC \uCD9C\uBC1C \uC6D0\uC815",
        ["AvailableContract"] = "\uC774\uC6A9 \uAC00\uB2A5 \uACC4\uC57D",
        ["LinkedDungeon"] = "\uC5F0\uACB0 \uB358\uC804",
        ["SelectedCity"] = "\uC120\uD0DD \uB3C4\uC2DC",
        ["CurrentCity"] = "\uD604\uC7AC \uB3C4\uC2DC",
        ["CityManaShardStock"] = "\uB9C8\uB098 \uC0E4\uB4DC \uC7AC\uACE0",
        ["NeedPressure"] = "\uC218\uC694 \uC555\uBC15\uB3C4",
        ["DispatchReadiness"] = "\uD30C\uACAC \uC900\uBE44\uB3C4",
        ["RecoveryProgress"] = "\uD68C\uBCF5 \uC9C4\uD589\uB3C4",
        ["ConsecutiveDispatches"] = "\uC5F0\uC18D \uD30C\uACAC \uD69F\uC218",
        ["DispatchPolicy"] = "\uD30C\uACAC \uC815\uCC45",
        ["CyclePolicy"] = "\uC815\uCC45 \uC804\uD658",
        ["RecommendedRoute"] = "\uCD94\uCC9C \uB8E8\uD2B8",
        ["RecommendedRouteForLinkedCity"] = "\uC5F0\uACB0 \uB3C4\uC2DC \uCD94\uCC9C \uB8E8\uD2B8",
        ["RecommendationReason"] = "\uCD94\uCC9C \uC0AC\uC720",
        ["RecoveryAdvice"] = "\uD68C\uBCF5 \uC870\uC5B8",
        ["ExpectedNeedImpact"] = "\uC608\uC0C1 \uC218\uC694 \uC601\uD5A5",
        ["LastDispatchImpact"] = "\uB9C8\uC9C0\uB9C9 \uD30C\uACAC \uC601\uD5A5",
        ["LastDispatchStockDelta"] = "\uB9C8\uC9C0\uB9C9 \uD30C\uACAC \uC7AC\uACE0 \uBCC0\uD654",
        ["LastNeedPressureChange"] = "\uB9C8\uC9C0\uB9C9 \uC218\uC694 \uC555\uBC15\uB3C4 \uBCC0\uD654",
        ["LastDispatchReadinessChange"] = "\uB9C8\uC9C0\uB9C9 \uD30C\uACAC \uC900\uBE44\uB3C4 \uBCC0\uD654",
        ["CityDispatchedFrom"] = "\uCD9C\uBC1C \uB3C4\uC2DC",
        ["FollowedRecommendation"] = "\uCD94\uCC9C \uB530\uB984 \uC5EC\uBD80",
        ["ManaShardsReturned"] = "\uBC18\uD658 \uB9C8\uB098 \uC0E4\uB4DC",
        ["StockBefore"] = "\uD30C\uACAC \uC804 \uC7AC\uACE0",
        ["StockAfter"] = "\uD30C\uACAC \uD6C4 \uC7AC\uACE0",
        ["StockDelta"] = "\uC7AC\uACE0 \uBCC0\uD654",
        ["NeedPressureBefore"] = "\uD30C\uACAC \uC804 \uC218\uC694 \uC555\uBC15\uB3C4",
        ["NeedPressureAfter"] = "\uD30C\uACAC \uD6C4 \uC218\uC694 \uC555\uBC15\uB3C4",
        ["DispatchReadinessBefore"] = "\uD30C\uACAC \uC804 \uD30C\uACAC \uC900\uBE44\uB3C4",
        ["DispatchReadinessAfter"] = "\uD30C\uACAC \uD6C4 \uD30C\uACAC \uC900\uBE44\uB3C4",
        ["RecoveryEta"] = "\uD68C\uBCF5 \uC608\uC0C1 \uC77C\uC218",
        ["EliteStatus"] = "\uC5D8\uB9AC\uD2B8 \uC0C1\uD0DC",
        ["EliteEncounter"] = "\uC5D8\uB9AC\uD2B8 \uC870\uC6B0",
        ["EliteType"] = "\uC5D8\uB9AC\uD2B8 \uC720\uD615",
        ["EliteHp"] = "\uC5D8\uB9AC\uD2B8 HP",
        ["EliteIntent"] = "\uC5D8\uB9AC\uD2B8 \uC758\uB3C4",
        ["EliteDefeated"] = "\uC5D8\uB9AC\uD2B8 \uCC98\uCE58",
        ["EliteName"] = "\uC5D8\uB9AC\uD2B8 \uC774\uB984",
        ["EliteReward"] = "\uC5D8\uB9AC\uD2B8 \uBCF4\uC0C1",
        ["EliteRewardStatus"] = "\uC5D8\uB9AC\uD2B8 \uBCF4\uC0C1 \uC0C1\uD0DC",
        ["EliteRewardHint"] = "\uC5D8\uB9AC\uD2B8 \uBCF4\uC0C1 \uD78C\uD2B8",
        ["EliteRewardIdentity"] = "\uC5D8\uB9AC\uD2B8 \uBCF4\uC0C1 \uB77C\uBCA8",
        ["EliteRewardAmount"] = "\uC5D8\uB9AC\uD2B8 \uBCF4\uC0C1\uB7C9",
        ["PanelDungeonPreElite"] = "\uC5D8\uB9AC\uD2B8 \uC804 \uCD5C\uC885 \uC120\uD0DD",
        ["PreEliteChoice"] = "\uC5D8\uB9AC\uD2B8 \uC804 \uC120\uD0DD",
        ["PreEliteHealAmount"] = "\uC5D8\uB9AC\uD2B8 \uC804 \uD68C\uBCF5\uB7C9",
        ["EliteBonusRewardEarned"] = "\uC5D8\uB9AC\uD2B8 \uCD94\uAC00 \uBCF4\uC0C1 \uD68D\uB4DD",
        ["EliteBonusRewardAmount"] = "\uC5D8\uB9AC\uD2B8 \uCD94\uAC00 \uBCF4\uC0C1\uB7C9",
        ["DungeonDanger"] = "\uB358\uC804 \uC704\uD5D8\uB3C4",
        ["RecommendedPower"] = "\uAD8C\uC7A5 \uC804\uB825",
        ["ExpeditionDurationDays"] = "\uC6D0\uC815 \uC18C\uC694\uC77C",
        ["RewardPreview"] = "\uBCF4\uC0C1 \uBBF8\uB9AC\uBCF4\uAE30",
        ["LastExpeditionResult"] = "\uB9C8\uC9C0\uB9C9 \uC6D0\uC815 \uACB0\uACFC",
        ["StepLabel"] = "Step DungeonRun-Batch-15: Elite Variant Pack + Post-Elite Reward Identity",
        ["EncounterRoomType"] = "\uC870\uC6B0 \uBC29 \uC720\uD615",
        ["Controls"] = "\uC870\uC791",
        ["ControlsValue"] = "[LMB] \uC120\uD0DD  [WASD/\uBC29\uD5A5\uD0A4] \uC774\uB3D9  [\uD720] \uC90C  [Esc] \uB4A4\uB85C",
        ["BoolOn"] = "\uCF1C\uC9D0",
        ["BoolOff"] = "\uAEBC\uC9D0",
        ["LanguageEnglish"] = "\uC601\uC5B4",
        ["LanguageKorean"] = "\uD55C\uAD6D\uC5B4"
    };

    public static string Get(PrototypeLanguage language, string key)
    {
        Dictionary<string, string> table = language == PrototypeLanguage.Korean ? KoreanByKey : EnglishByKey;
        return table.TryGetValue(key, out string value) ? value : key;
    }

    public static string GetLanguageDisplayName(PrototypeLanguage language)
    {
        return language == PrototypeLanguage.Korean
            ? Get(language, "LanguageKorean")
            : Get(language, "LanguageEnglish");
    }

    public static string TranslateValue(PrototypeLanguage language, string text)
    {
        return text;
    }
}









